serve:
  hostname: ${GATEWAY_HOSTNAME}
  port: ${GATEWAY_PORT}
sources:
  - name: CourseService
    handler:
      graphql:
        endpoint: "{env.COURSE_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
  - name: ContentService
    handler:
      graphql:
        endpoint: "{env.CONTENT_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
  - name: MediaService
    handler:
      graphql:
        endpoint: "{env.MEDIA_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
  - name: FlashcardService
    handler:
      graphql:
        endpoint: "{env.FLASHCARD_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"    
  - name: RewardService
    handler:
      graphql:
        endpoint: "{env.REWARD_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
  - name: UserService
    handler:
      graphql:
        endpoint: "{env.USER_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
  - name: QuizService
    handler:
      graphql:
        endpoint: "{env.QUIZ_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
  - name: SkilllevelService
    handler:
      graphql:
        endpoint: "{env.SKILLLEVEL_SERVICE_URL}"
        operationHeaders:
          CurrentUser: "{context.currentUserJson}"
additionalTypeDefs:
  - "./additionalTypeDefs/content.graphqls"
  - "./additionalTypeDefs/course.graphqls"
  - "./additionalTypeDefs/flashcard.graphqls"
  - "./additionalTypeDefs/rewards.graphqls"
  - "./additionalTypeDefs/skill_level.graphqls"
  - "./additionalTypeDefs/user.graphqls"
additionalResolvers:
  - "./additionalResolvers/content.ts"
  - "./additionalResolvers/course.ts"
additionalEnvelopPlugins: "./envelopPlugins"
transforms:
  - filterSchema:
      mode: bare
      filters:
        - Mutation.!_internal* # filter out all mutations that start with _internal
        - Query.!_internal* # filter out all queries that start with _internal