version: '3.7'

services:
  gateway:
    build:
      context: ./../graphql_gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: gateway
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      GATEWAY_HOSTNAME: "0.0.0.0"
      GATEWAY_PORT: "8080"
      COURSE_SERVICE_URL: http://app-course:2001/graphql
      MEDIA_SERVICE_URL: http://app-media:3001/graphql
      CONTENT_SERVICE_URL: http://app-content:4001/graphql
      USER_SERVICE_URL: http://app-user:5001/graphql
      FLASHCARD_SERVICE_URL: http://app-flashcard:6001/graphql
      REWARD_SERVICE_URL: http://app-reward:7001/graphql
      SKILLLEVEL_SERVICE_URL: http://app-skilllevel:8001/graphql
      QUIZ_SERVICE_URL: http://app-quiz:9001/graphql
      DOCPROCAI_SERVICE_URL: http://app-docprocai:9901/graphql/
      DEBUG: 0
      ENABLE_LOGGING: 1 # Set to 1 to enable custom logging
    networks:
      - dapr-network
    extra_hosts:
      # Required for Docker on Linux to resolve host.docker.internal to machine's localhost
      # Source: https://stackoverflow.com/a/24326540
      - "host.docker.internal:host-gateway"
networks:
  dapr-network:
    external: true
